# 12th MAR

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({'col1' : [1,2,3,4,5],
              'col2' : [45,56,67,34,34],
              'col3': "sudhanshu kumar krish ineuron one".split()
     })
df

# It is converting keys of Dict into the column and value as data.

col1  col2       col3
0     1    45  sudhanshu
1     2    56      kumar
2     3    67      krish
3     4    34    ineuron
4     5    34        one

In [3]:
"sudhanshu kumar krish ineuron one".split()

['sudhanshu', 'kumar', 'krish', 'ineuron', 'one']

In [4]:
df['col4'] = df['col1']**2

In [5]:
df

col1  col2       col3  col4
0     1    45  sudhanshu     1
1     2    56      kumar     4
2     3    67      krish     9
3     4    34    ineuron    16
4     5    34        one    25

In [10]:
df['col5'] = df['col3'].str[0]
df

col1  col2       col3  col4 col5
0     1    45  sudhanshu     1    s
1     2    56      kumar     4    k
2     3    67      krish     9    k
3     4    34    ineuron    16    i
4     5    34        one    25    o

In [11]:
def test(a) :
    return a**2

In [13]:
df['col4_4']  = df['col1'].apply(test)
df

col1  col2       col3  col4 col5  col4_4
0     1    45  sudhanshu     1    s       1
1     2    56      kumar     4    k       4
2     3    67      krish     9    k       9
3     4    34    ineuron    16    i      16
4     5    34        one    25    o      25

In [14]:
def test1(a):
    if a =='s':
        return 's'
    else:
        return 'z'

In [15]:
df['col6'] = df['col5'].apply(test1)
df

col1  col2       col3  col4 col5  col4_4 col6
0     1    45  sudhanshu     1    s       1    s
1     2    56      kumar     4    k       4    z
2     3    67      krish     9    k       9    z
3     4    34    ineuron    16    i      16    z
4     5    34        one    25    o      25    z

In [16]:
df['col7'] = df['col3'].apply(len)
df

# here we call len function inside the apply function thats why we are not writing apply(len()), we are writing
# apply(len) this.

col1  col2       col3  col4 col5  col4_4 col6  col7
0     1    45  sudhanshu     1    s       1    s     9
1     2    56      kumar     4    k       4    z     5
2     3    67      krish     9    k       9    z     5
3     4    34    ineuron    16    i      16    z     7
4     5    34        one    25    o      25    z     3

In [18]:
import math

df['col8'] = df['col2'].apply(math.log)
df

col1  col2       col3  col4 col5  col4_4 col6  col7      col8
0     1    45  sudhanshu     1    s       1    s     9  3.806662
1     2    56      kumar     4    k       4    z     5  4.025352
2     3    67      krish     9    k       9    z     5  4.204693
3     4    34    ineuron    16    i      16    z     7  3.526361
4     5    34        one    25    o      25    z     3  3.526361

In [ ]:
# Go and Open the 15.2 after this.

# PANDAS PROFILING ----> THIS TOPIC IS REMANING.

# NUMPY (Numeric Python)

In [19]:
# It is very imp that at the end of the day weather it's image,weather its mp4 file you are going to take for
# ML training operation it is going to convert every thing into the array format,because system doesnt undersatnd
# your mp4 format or pandas or images. Every thing is just array and metricses for a system. Because system is 
# suppose to do calculation.

# At starting it is not included as lib. in python but for calculation of array and metricses it is used and
# for that it is included.

# Inside the python they created another lib. called as Numpy so where they are trying to implement each and 
# every function which is available inside the Matlab.

In [20]:
import numpy as np

In [28]:
l = ["sudh",1,2,3,4]
print(type(l))
print(l)

<class 'list'>
['sudh', 1, 2, 3, 4]


In [26]:
np.array(l) # Here We convert list into array by simply calling l into the np.array().

# here in o/p we get u21 it is datatype of datatype.

array(['sudh', '1', '2', '3', '4'], dtype='<U21')

In [22]:
type(np.array(l)) # we get type as ndarray i.e. called as n dimension.

numpy.ndarray

In [29]:
a1 = np.array([3,4,5,6,3.0])
a1

# It convert all int no. into the floating point no. 

array([3., 4., 5., 6., 3.])

In [25]:
a = np.array([[1,2] , [3,4]])
a

array([[1, 2],
       [3, 4]])

In [30]:
a[1][1]

4

In [31]:
a2 = np.array([1,2,3,4],ndmin = 4) # 4 dimension array.
a2

array([[[[1, 2, 3, 4]]]])

In [32]:
a2[0]

array([[[1, 2, 3, 4]]])

In [33]:
a2[0][0]

array([[1, 2, 3, 4]])

In [34]:
a2[0][0][0]

array([1, 2, 3, 4])

In [35]:
a2[0][0][0][0]

1

In [36]:
b=np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [37]:
b1=np.asarray([1,2,3,4])
b1

array([1, 2, 3, 4])

In [39]:
b2=np.asanyarray([1,2,3,4])
b2

# 2 cells above whatever o/p is comming is the same o/p of this present cell.

array([1, 2, 3, 4])

In [ ]:
# Note:- Array allways be 1D or 2D or 3D etc.

# Note:- Matrix allways be in 2D.
# D---> Dimension.

# Matrix is a child form of array.

In [41]:
c=np.mat([1,2,3,4,5])
c

matrix([[1, 2, 3, 4, 5]])

In [43]:
e=[1,2,3,4,5,6,7,8]

e1=np.asarray(e)
e1

# here we pass list inside the "asarray" in same cell and "asanyarray" in following cell.then it is coverting 
# list into the array.

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
e2=np.asanyarray([1,2,3,4,5,6,7,8])
e2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
# Now see here,we put list into the mat and coverted itself into the matrix form.

# And as we konw that Matrix is a child form of array means it is indirectly an array.

e3=np.mat(e)
e3
print(e3)
print(type(e3))

[[1 2 3 4 5 6 7 8]]
<class 'numpy.matrix'>


In [50]:
# now see if we call e3 in asanyarray so it is not coverting it into the array because it is allready in array
# because as we converted it into the matrix in above cell and we know that Matrix is a child form of array .

e4=np.asanyarray(np.mat(e))
e4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
np.fromfunction(lambda i , j : i==j , (3,3))

# j | 0   1   2
# --|---------------
# i  |-       -|
# 0  |T   F   F|
# 1  |F   T   F|
# 2  |F   F   T|
#    |-       -|

# o/p is in array

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [53]:
np.fromfunction(lambda i , j : i*j , (4,4),dtype=int)

# o/p is in array

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [54]:
# To convert above into the mat then

np.mat(np.fromfunction(lambda i , j : i*j , (4,4),dtype=int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [55]:
np.mat(np.fromfunction(lambda i , j : i*j , (3,3,2),dtype=int))

# It will not work.

TypeError: <lambda>() takes 2 positional arguments but 3 were given

In [56]:
np.mat(np.fromfunction(lambda i,j,z : i*j*z , (3,3,2),dtype=int))

# Again it will not work.

# lambda function is no taking 3 array at a time means it is not making 3d matrixes.

ValueError: shape too large to be a matrix.

In [59]:
# Now we will remove np.mat() and then see

np.fromfunction(lambda i,j,z : i*j*z , (3,3,3),dtype=int)

# here (3,3,3) means 
#      |  |__|-------> Of 3*3 
#      |  
#      |____> It mean 3 matrixes

# array([[[0, 0, 0],
          [0, 0, 0],    -------> M1
          [0, 0, 0]],

          [[0, 0, 0],
          [0, 1, 2],    -------> M2
          [0, 2, 4]],

          [[0, 0, 0],
          [0, 2, 4],    --------> M3
#         [0, 4, 8]]])


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [60]:
np.fromfunction(lambda i,j,z : i*j*z ,(3,3,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [61]:
np.fromfunction(lambda i,j,z : i*j*z ,(4,3,2) ,dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [64]:
# IMP

np.fromfunction(lambda i,j,z,p : i*j*z*p ,(4,3,2,2) ,dtype = int)

#  (4,3,2,2)
#   | | |_| ----> having 2*2 matrix
#   | |____> of 3 array
#   |___>4 bunddle 

# 4 bunddle of 3 aaray having 2*2 matrix.
#
array([[[[0, 0],          # A1
         [0, 0]],

        [[0, 0],                             # 1st Bundle
         [0, 0]],         # A2

        [[0, 0],
         [0, 0]]],        # A3


       [[[0, 0],
         [0, 0]],         # A1

        [[0, 0],
         [0, 1]],         # A2               # 2nd bundle

        [[0, 0],
         [0, 2]]],        # A3


       [[[0, 0],          # A1
         [0, 0]],

        [[0, 0],
         [0, 2]],         # A2               # 3rd bundle

        [[0, 0],
         [0, 4]]],        # A3


       [[[0, 0],          # A1
         [0, 0]],

        [[0, 0],          # A2                # 4th bundle
         [0, 3]],

        [[0, 0],
         0, 6]]]])        # A3   
#        

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [65]:
a = np.fromfunction(lambda i,j,z : i*j*z ,(4,3,2) ,dtype = int)
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [66]:
a.ndim  # It tells us dimension.

3

In [67]:
a.size  # It tells us total elements.

24

In [68]:
a.shape

(4, 3, 2)

In [69]:
a.dtype

dtype('int64')

In [70]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [72]:
pd.DataFrame(a)

# It is not goning to work. because dataframes are 2d. so thats why it is saying that 
# ValueError: Must pass 2-d input shape=(4, 3, 2)


ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [73]:
a = np.fromfunction(lambda i , j : i*j , (4,3),dtype = int)
a

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [74]:
pd.DataFrame(a)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [77]:
a12 = np.fromfunction(lambda i , j : i*j , (400,100),dtype = int)
a12

array([[    0,     0,     0, ...,     0,     0,     0],
       [    0,     1,     2, ...,    97,    98,    99],
       [    0,     2,     4, ...,   194,   196,   198],
       ...,
       [    0,   397,   794, ..., 38509, 38906, 39303],
       [    0,   398,   796, ..., 38606, 39004, 39402],
       [    0,   399,   798, ..., 38703, 39102, 39501]])

In [78]:
pd.DataFrame(a12)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]

In [ ]:
#  randint , rand , randn 

In [80]:
# randint
np.random.randint(4,50)

17

In [79]:
# rand
# np.random.rand(row,column)

np.random.rand(100,4) #(row,column)

array([[8.80412155e-02, 9.75030506e-01, 2.48846969e-01, 4.63925226e-01],
       [2.94206605e-01, 8.77595224e-01, 3.16893034e-01, 5.89161986e-01],
       [8.03918604e-01, 2.62186134e-02, 9.76713439e-01, 7.58609466e-01],
       [1.09528491e-01, 1.39889415e-01, 3.41082157e-01, 6.84547892e-02],
       [9.25558989e-01, 4.67514442e-02, 1.51625630e-01, 7.86339959e-01],
       [7.27831483e-01, 2.74612160e-01, 7.09696180e-01, 6.12686405e-01],
       [6.29523793e-01, 9.91373394e-01, 8.36896815e-01, 4.53397518e-01],
       [9.69755281e-01, 7.71689157e-01, 5.83597681e-01, 3.46288225e-01],
       [2.61221184e-01, 1.79418010e-01, 3.57938044e-01, 9.90332913e-01],
       [3.88008168e-02, 9.89539994e-01, 7.43672694e-01, 1.33156716e-01],
       [3.61649733e-01, 1.30158281e-01, 6.34847094e-01, 4.61142186e-01],
       [5.95045550e-01, 1.76234805e-04, 9.04031441e-01, 6.06566339e-01],
       [3.69168820e-01, 1.37517496e-01, 4.57597184e-01, 9.03228558e-01],
       [1.56935979e-01, 3.57647922e-01, 8.95583174e

In [81]:
# randn 
np.random.randn(4,5)

array([[-0.06380923,  0.63410693, -1.31428359, -1.54230957,  1.02274975],
       [-0.26841336,  0.83605946,  0.54807151,  0.21939353, -0.10549623],
       [-1.2421327 , -0.06383376, -1.27417985,  0.32152864, -0.62758717],
       [-0.75827706, -0.19746368,  0.83039699,  0.20750189,  0.26456503]])

In [82]:
# see the difference between "rand" and "randn"...

# "rand" allways try to give you simple random distribution.

# "randn" allways give us random no but with a normal distribution, if we try to find Avg of these no. then it 
# will be zero and std. deviation of these no. is 1.

In [83]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -1.152245  2.208295  0.276000  0.950356 -1.374094
1 -1.346540 -0.073251 -0.597684  0.417965 -0.004079
2 -1.188084  0.258371 -0.473430  0.351107  0.368040
3 -0.295426  0.550181  0.778677  2.387742 -0.457649

In [7]:
import numpy as np

In [8]:
# as we see error in this 

a6 = np.fromfunction(lambda i,j,z : i*j*z , (4,3,2),dtype = int)
a6

pd.DataFrame(a6)

# so to resolve this we can convert 3D into the 2D.

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [9]:
a6 # As here 24 elements are there.

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [10]:
a6.size

24

In [88]:
a6.reshape(8,3) # while reshaping it we have to give row no. and column no. in such a way that there 
# multiplication should be as same as total no. of elements.

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 2],
       [0, 0, 0],
       [2, 0, 4],
       [0, 0, 0],
       [3, 0, 6]])

In [89]:
pd.DataFrame(a6.reshape(8,3)) # Now we can convert it into the dataframe.

0  1  2
0  0  0  0
1  0  0  0
2  0  0  0
3  1  0  2
4  0  0  0
5  2  0  4
6  0  0  0
7  3  0  6

In [90]:
a6.reshape(4,-1) # Here -1 represent 6 over here because -1 means it will take that number whoes
# multiplication with 4 gives us 24.

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [91]:
a6.reshape(5,-1) # here we will get error because we can't get 24 when if we try to multiply 5 with any no. 


ValueError: cannot reshape array of size 24 into shape (5,newaxis)

In [93]:
a6.reshape(2,4,-234)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [94]:
list(range(4,10,2))

[4, 6, 8]

In [96]:
list(range(4,10,.2))

TypeError: 'float' object cannot be interpreted as an integer

In [97]:
np.arange(4,10,.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [99]:
df12=np.arange(4,10.5,.2)
df12

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [100]:
df12[1:4]

array([4.2, 4.4, 4.6])

In [102]:
arr = np.random.rand(4,5)
arr

array([[0.21161058, 0.04931553, 0.27294957, 0.63617059, 0.8367505 ],
       [0.68345656, 0.06196763, 0.81169615, 0.25077841, 0.08325957],
       [0.9392098 , 0.84927139, 0.388384  , 0.39799466, 0.09838074],
       [0.80242679, 0.6513403 , 0.614134  , 0.54631429, 0.78944353]])

In [103]:
arr[arr > .5]

array([0.63617059, 0.8367505 , 0.68345656, 0.81169615, 0.9392098 ,
       0.84927139, 0.80242679, 0.6513403 , 0.614134  , 0.54631429,
       0.78944353])

In [104]:
arr

array([[0.21161058, 0.04931553, 0.27294957, 0.63617059, 0.8367505 ],
       [0.68345656, 0.06196763, 0.81169615, 0.25077841, 0.08325957],
       [0.9392098 , 0.84927139, 0.388384  , 0.39799466, 0.09838074],
       [0.80242679, 0.6513403 , 0.614134  , 0.54631429, 0.78944353]])

In [105]:
# arr[[row] , [column]]

arr[[1,2],[2]]

array([0.81169615, 0.388384  ])

In [106]:
arr = np.random.rand(8,5)
arr

array([[0.23508358, 0.229365  , 0.76788097, 0.27017667, 0.54872973],
       [0.77280844, 0.47600454, 0.23779443, 0.71340244, 0.14996494],
       [0.52678942, 0.62778763, 0.25130103, 0.56628581, 0.33264334],
       [0.78414358, 0.24776204, 0.64883727, 0.65656541, 0.69907145],
       [0.83270561, 0.76694594, 0.01899904, 0.54691002, 0.77473641],
       [0.69346757, 0.00582678, 0.08417453, 0.81820164, 0.1711954 ],
       [0.236567  , 0.15191036, 0.50114109, 0.73655285, 0.01125851],
       [0.09753952, 0.32357036, 0.16548257, 0.34747776, 0.20138492]])

In [107]:
arr[1:8,0:3]

array([[0.77280844, 0.47600454, 0.23779443],
       [0.52678942, 0.62778763, 0.25130103],
       [0.78414358, 0.24776204, 0.64883727],
       [0.83270561, 0.76694594, 0.01899904],
       [0.69346757, 0.00582678, 0.08417453],
       [0.236567  , 0.15191036, 0.50114109],
       [0.09753952, 0.32357036, 0.16548257]])

In [111]:
a2 = arr[1:8,[0,1,2]]
a2

array([[0.77280844, 0.47600454, 0.23779443],
       [0.52678942, 0.62778763, 0.25130103],
       [0.78414358, 0.24776204, 0.64883727],
       [0.83270561, 0.76694594, 0.01899904],
       [0.69346757, 0.00582678, 0.08417453],
       [0.236567  , 0.15191036, 0.50114109],
       [0.09753952, 0.32357036, 0.16548257]])

In [109]:
a2[0][0] = 100

In [110]:
a2

array([[1.00000000e+02, 4.76004540e-01, 2.37794434e-01],
       [5.26789415e-01, 6.27787626e-01, 2.51301032e-01],
       [7.84143584e-01, 2.47762037e-01, 6.48837272e-01],
       [8.32705606e-01, 7.66945943e-01, 1.89990409e-02],
       [6.93467574e-01, 5.82677975e-03, 8.41745303e-02],
       [2.36567003e-01, 1.51910363e-01, 5.01141094e-01],
       [9.75395225e-02, 3.23570358e-01, 1.65482574e-01]])

In [112]:
a = np.array([[1,2] ,[3,4]])
b = np.array([[2,3] , [4,5]])

In [113]:
a

array([[1, 2],
       [3, 4]])

In [114]:
b

array([[2, 3],
       [4, 5]])

In [115]:
a*b    
# It just elements wise multiplication.

array([[ 2,  6],
       [12, 20]])

In [118]:
m = a@b 
m
# Here it is matrix multiplication. It is very much imp in D.L.

array([[10, 13],
       [22, 29]])

In [122]:
type(m)

numpy.ndarray

In [120]:
m/0 # It will not give error.

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf],
       [inf, inf]])

In [121]:
m/2

array([[ 5. ,  6.5],
       [11. , 14.5]])

# 13MAR

In [123]:
import numpy as np 

In [124]:
l = [1,2,3,4,54]

In [125]:
np.asarray(l)

array([ 1,  2,  3,  4, 54])

In [126]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [127]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [128]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [129]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [130]:
np.ones((3,6,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [131]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [132]:
np.empty((4,5)) # Here in array see the no. all are very small no. means it is equal to 0 ie. equal to empty.

array([[0.21161058, 0.04931553, 0.27294957, 0.63617059, 0.8367505 ],
       [0.68345656, 0.06196763, 0.81169615, 0.25077841, 0.08325957],
       [0.9392098 , 0.84927139, 0.388384  , 0.39799466, 0.09838074],
       [0.80242679, 0.6513403 , 0.614134  , 0.54631429, 0.78944353]])

In [133]:
np.empty((4,5,2))

array([[[0.23508358, 0.229365  ],
        [0.76788097, 0.27017667],
        [0.54872973, 0.77280844],
        [0.47600454, 0.23779443],
        [0.71340244, 0.14996494]],

       [[0.52678942, 0.62778763],
        [0.25130103, 0.56628581],
        [0.33264334, 0.78414358],
        [0.24776204, 0.64883727],
        [0.65656541, 0.69907145]],

       [[0.83270561, 0.76694594],
        [0.01899904, 0.54691002],
        [0.77473641, 0.69346757],
        [0.00582678, 0.08417453],
        [0.81820164, 0.1711954 ]],

       [[0.236567  , 0.15191036],
        [0.50114109, 0.73655285],
        [0.01125851, 0.09753952],
        [0.32357036, 0.16548257],
        [0.34747776, 0.20138492]]])

In [134]:
np.linspace(2,6)

# It takes start point and it will take end points and generate some of the values in between.

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [137]:
# np.linspace(start point,End point,number of No.which we want) 
np.linspace(2,6,10)
# it allways generate single dimension no.

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [138]:
np.linspace(2,6,100) # here it will take upper bound no ie. 6 over here

array([2.        , 2.04040404, 2.08080808, 2.12121212, 2.16161616,
       2.2020202 , 2.24242424, 2.28282828, 2.32323232, 2.36363636,
       2.4040404 , 2.44444444, 2.48484848, 2.52525253, 2.56565657,
       2.60606061, 2.64646465, 2.68686869, 2.72727273, 2.76767677,
       2.80808081, 2.84848485, 2.88888889, 2.92929293, 2.96969697,
       3.01010101, 3.05050505, 3.09090909, 3.13131313, 3.17171717,
       3.21212121, 3.25252525, 3.29292929, 3.33333333, 3.37373737,
       3.41414141, 3.45454545, 3.49494949, 3.53535354, 3.57575758,
       3.61616162, 3.65656566, 3.6969697 , 3.73737374, 3.77777778,
       3.81818182, 3.85858586, 3.8989899 , 3.93939394, 3.97979798,
       4.02020202, 4.06060606, 4.1010101 , 4.14141414, 4.18181818,
       4.22222222, 4.26262626, 4.3030303 , 4.34343434, 4.38383838,
       4.42424242, 4.46464646, 4.50505051, 4.54545455, 4.58585859,
       4.62626263, 4.66666667, 4.70707071, 4.74747475, 4.78787879,
       4.82828283, 4.86868687, 4.90909091, 4.94949495, 4.98989

In [141]:
np.linspace(2,6,10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [140]:
np.linspace(2,6,10,endpoint=False)

array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6])

In [143]:
np.linspace(2,6,10,endpoint=False,retstep=True) 

# restep wlll show step size also what he take internally. i.e. here it is 0.4

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [145]:
np.logspace(2,4,10,base=2)

# It is same as linespace but it will generate log value of no. which we have mention in it.

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [146]:
np.logspace(2,4,10,base=10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [148]:
a = np.arange(4,40).reshape(6,6)
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [150]:
a.max() # It will give us single value from complete array.

39

In [151]:
a.max(axis = 0) # It will give complete row having max value.

array([34, 35, 36, 37, 38, 39])

In [152]:
a.max(axis = 1) # It will give complete row having max value.

array([ 9, 15, 21, 27, 33, 39])

In [153]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [154]:
10+a

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [155]:
a/0

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [156]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [157]:
a**3

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]])

In [158]:
pow(a,3)

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]])

In [159]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [211]:
b = np.array([2,3,1,2,3,4])
b

array([2, 3, 1, 2, 3, 4])

In [161]:
a+b   # Here it will do operation row wise.

array([[ 6,  8,  7,  9, 11, 13],
       [12, 14, 13, 15, 17, 19],
       [18, 20, 19, 21, 23, 25],
       [24, 26, 25, 27, 29, 31],
       [30, 32, 31, 33, 35, 37],
       [36, 38, 37, 39, 41, 43]])

In [172]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [212]:
b 

array([2, 3, 1, 2, 3, 4])

In [214]:
b=b.T # Transpose operation is not happening.
b

array([2, 3, 1, 2, 3, 4])

In [215]:
a+b # see it is not doing column wise operation 

# so for that do the following operation.

array([[ 6,  8,  7,  9, 11, 13],
       [12, 14, 13, 15, 17, 19],
       [18, 20, 19, 21, 23, 25],
       [24, 26, 25, 27, 29, 31],
       [30, 32, 31, 33, 35, 37],
       [36, 38, 37, 39, 41, 43]])

In [216]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [ ]:
b # It is 1D array.

In [164]:
b=b.reshape(1,-1)
b
# Now we converted into the 2D array.

array([[2, 3, 1, 2, 3, 4]])

In [170]:
b=b.T
b 
# Here we transpose it.

array([[2],
       [3],
       [1],
       [2],
       [3],
       [4]])

In [171]:
a+b

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [38, 39, 40, 41, 42, 43]])

In [173]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [174]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [175]:
np.exp(a)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [176]:
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [177]:
# Concept of Deep Copy and Shallo copy

In [178]:
x = np.array([1,2,3])

In [179]:
y = x # Shallo Copy

In [180]:
y

array([1, 2, 3])

In [181]:
z = np.copy(x) # Deep Copy

In [182]:
z

array([1, 2, 3])

In [183]:
x[0] = 100

In [184]:
y

array([100,   2,   3])

In [185]:
z

array([1, 2, 3])

In [186]:
id(z)

140569929674352

In [187]:
id(x)

140569929250256

In [189]:
id(y)

140569929250256

In [190]:
import numpy as np

In [191]:
su = np.array([567,345])

In [192]:
df = su

In [193]:
id(su)

140569929724624

In [194]:
id(df)

140569929724624

In [195]:
id(su[0])

140569929690096

In [196]:
id(df[0])

140569929690192

In [197]:
id(su[1])

140569929690352

In [198]:
id(df[1])

140569929690480

In [199]:
id(su[0]) == id(df[0])

True

In [200]:
id(su[1]) == id(df[0])

True

In [201]:
id(su) == id(df)

True

In [202]:
xt = np.array([34,67,89])

In [203]:
id(xt[0]) == id(su[0])

True

In [204]:
c = "sudh"

In [205]:
id(c) == id(su[0])

False

In [ ]:
# Open file number 15.1