# 11th JUL

In [ ]:
# This is from previous batch recording.

In [1]:
import numpy as np
import array

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [4]:
np.array([1,2,3,4,5,"sudh" , 4+8j,])

# Here array is converting all values into the string value.

array(['1', '2', '3', '4', '5', 'sudh', '(4+8j)'], dtype='<U64')

In [5]:
np.array([1,2,3,4.5,6.0])

# Here array is converting all numerical values into the floating point no.

array([1. , 2. , 3. , 4.5, 6. ])

In [6]:
np.array([[1,3],[3,4]])

# Here we gave data into list.

# OR we can give data in tuple also. see on next cell.

array([[1, 3],
       [3, 4]])

In [13]:
np.array([(1,2),(4,5)])

array([[1, 2],
       [4, 5]])

In [7]:
np.array([[1,3],[3,4],[6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [9]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [8]:
np.array([[1,3],[3,4],[6,7,8]])

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [10]:
np.array([1,2,3] , ndmin = 3)

array([[[1, 2, 3]]])

In [11]:
np.array([1,2,3] , dtype = complex)

# Here we can do the type casting also.

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
arr  = np.array([[1,3],[3,4]])
arr

array([[1, 3],
       [3, 4]])

In [16]:
arr[0][1]

3

In [17]:
type(arr[0][1])

numpy.int64

In [21]:
mat=np.mat(arr)
mat

matrix([[1, 3],
        [3, 4]])

In [ ]:
# OR

In [22]:
mat = np.matrix(arr)
mat

matrix([[1, 3],
        [3, 4]])

In [25]:
l = [3,4,5,76,7]

# We can convert list into array by using np.array(),np.asarray(),np.asanyarray().

In [26]:
np.array(l)

array([ 3,  4,  5, 76,  7])

In [27]:
np.asarray(l)

array([ 3,  4,  5, 76,  7])

In [28]:
np.asanyarray(l)

array([ 3,  4,  5, 76,  7])

In [29]:
mat=np.mat(arr)
mat

matrix([[1, 3],
        [3, 4]])

In [30]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 4]])

In [31]:
# If we want a proof that weather matrix is subform/subclass of array.

issubclass(np.ndarray,np.matrix)

# "False" in o/p  means ndarray is not sub class of matrix.

False

In [32]:
issubclass(np.matrix,np.ndarray)

# "True" in o/p  means matrix is sub class of ndarray.

True

In [36]:
arr

array([[1, 3],
       [3, 4]])

In [37]:
a=arr  

In [38]:
b = np.copy(arr) 

In [39]:
arr[0][0] = 67
arr

array([[67,  3],
       [ 3,  4]])

In [40]:
a

array([[67,  3],
       [ 3,  4]])

In [41]:
b

array([[1, 3],
       [3, 4]])

In [42]:
arr[-1]

array([3, 4])

In [43]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [44]:
np.fromfunction(lambda i,j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [45]:
type(np.fromfunction(lambda i,j :i==j,(4,4)))

numpy.ndarray

In [46]:
np.fromfunction(lambda i,j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [47]:
np.fromfunction(lambda i,j :i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [49]:
0/0

ZeroDivisionError: division by zero

In [50]:
1/0

ZeroDivisionError: division by zero

In [48]:
np.fromfunction(lambda i,j :i/j,(3,3))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [ ]:
# Here in above we are not getting error. because we have done calculation in numpy.

In [53]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [54]:
(i*i for i in range(5))

# OR

<generator object <genexpr> at 0x7faf85b1d6d0>

In [55]:
def test(x):
    yield x 
    
test(5)

# OR

<generator object test at 0x7faf85b1d750>

In [61]:
gen=(i*i for i in range(5))
gen

<generator object <genexpr> at 0x7faf85b1dbd0>

In [62]:
for i in gen:
    print(i)

0
1
4
9
16


In [67]:
np.fromiter(gen,dtype= int)

array([5])

In [64]:
np.fromiter(range(5),dtype= int)

array([0, 1, 2, 3, 4])

In [65]:
np.fromstring('1,3,4,5,5',sep = ',', dtype= int)

array([1, 3, 4, 5, 5])

In [66]:
np.fromstring("456 456 3454 34543",sep = ' ', dtype= complex)

array([  456.+0.j,   456.+0.j,  3454.+0.j, 34543.+0.j])

In [3]:
import numpy as np

In [4]:
l = [3,4,5,6,7,8]

In [6]:
arr = np.array(l)
arr

array([3, 4, 5, 6, 7, 8])

In [7]:
arr1 = np.array([[1,2,3,4] , [2,3,4,5] , [4,5,6,7]])
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(arr1)

numpy.ndarray

In [10]:
arr.ndim # dimension

1

In [11]:
arr.size # Total No of elements.

6

In [12]:
arr.shape # 3rows 4colunm.

(6,)

In [78]:
arr.dtype # Type

dtype('int64')

In [79]:
arr1.ndim

2

In [80]:
arr1.size

12

In [81]:
arr1.shape

(3, 4)

In [82]:
arr1.dtype

dtype('int64')

In [84]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]] , [[1,2,3,4],[4,5,6,7]]])
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [85]:
arr2.ndim

3

In [86]:
arr2.size

16

In [87]:
arr2.shape  

(2, 2, 4)

In [88]:
arr2.dtype

dtype('int64')

In [101]:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]] , [[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [102]:
arr4.ndim

4

In [103]:
arr4.size

32

In [104]:
arr4.shape

(1, 4, 2, 4)

In [105]:
arr4.dtype

dtype('int64')

In [106]:
list(range(5))

[0, 1, 2, 3, 4]

In [107]:
list(range(6.6,9,.3))

TypeError: 'float' object cannot be interpreted as an integer

In [109]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [110]:
np.arange(6.6,9,.3) # In case of floating value upper bound (9) is going to consider.

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [114]:
np.arange(6.6,9,-.3) # It will give us blank as we aware about the scaling concept.+ve/-ve direction

array([], dtype=float64)

In [113]:
np.arange(9,6.6,-.3) # In case of floating value upper bound (6.6) is going to consider.

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [15]:
np.arange(6,9,2) # In case of int value upper bound (9) is not going to consider.

array([6, 8])

In [16]:
np.arange(6,9,-2)  # It will give us blank as we aware about the scaling concept.+ve/-ve direction.

array([], dtype=int64)

In [115]:
np.linspace(1,10,5)  # It means produce 5 value between 1,10 with equal differences.

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [116]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [117]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [125]:
np.zeros((2,5,4,1))

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [118]:
np.ones(4)

array([1., 1., 1., 1.])

In [128]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [119]:
np.ones((2,3,1)) + 5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [120]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [121]:
np.empty((3,4))

array([[0.00000000e+000, 2.96439388e-323, 0.00000000e+000,
        0.00000000e+000],
       [8.48798316e-313, 6.82116729e-043, 7.73684658e-091,
        4.74989402e-037],
       [2.36689902e+179, 4.11633523e+179, 3.99910963e+252,
        1.16187641e+295]])

In [122]:
np.eye(3) # Identity matrix. 3 means (3*3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [134]:
np.linspace(1,6,4,endpoint=False,axis=0)

array([1.  , 2.25, 3.5 , 4.75])

In [135]:
np.linspace(1,6,4,endpoint=False,axis=1) # It will give us error.

AxisError: destination: axis 1 is out of bounds for array of dimension 1

In [24]:
np.linspace([1,6],4,endpoint=False,axis=0) #??

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [23]:
np.linspace([1,6],4,endpoint=False,axis=1) #??

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [146]:
np.linspace([1,6],4,endpoint=True,axis=0)

array([[1.        , 6.        ],
       [1.06122449, 5.95918367],
       [1.12244898, 5.91836735],
       [1.18367347, 5.87755102],
       [1.24489796, 5.83673469],
       [1.30612245, 5.79591837],
       [1.36734694, 5.75510204],
       [1.42857143, 5.71428571],
       [1.48979592, 5.67346939],
       [1.55102041, 5.63265306],
       [1.6122449 , 5.59183673],
       [1.67346939, 5.55102041],
       [1.73469388, 5.51020408],
       [1.79591837, 5.46938776],
       [1.85714286, 5.42857143],
       [1.91836735, 5.3877551 ],
       [1.97959184, 5.34693878],
       [2.04081633, 5.30612245],
       [2.10204082, 5.26530612],
       [2.16326531, 5.2244898 ],
       [2.2244898 , 5.18367347],
       [2.28571429, 5.14285714],
       [2.34693878, 5.10204082],
       [2.40816327, 5.06122449],
       [2.46938776, 5.02040816],
       [2.53061224, 4.97959184],
       [2.59183673, 4.93877551],
       [2.65306122, 4.89795918],
       [2.71428571, 4.85714286],
       [2.7755102 , 4.81632653],
       [2.

In [143]:
np.linspace([1,6],4,endpoint=True,axis=1)

array([[1.        , 1.06122449, 1.12244898, 1.18367347, 1.24489796,
        1.30612245, 1.36734694, 1.42857143, 1.48979592, 1.55102041,
        1.6122449 , 1.67346939, 1.73469388, 1.79591837, 1.85714286,
        1.91836735, 1.97959184, 2.04081633, 2.10204082, 2.16326531,
        2.2244898 , 2.28571429, 2.34693878, 2.40816327, 2.46938776,
        2.53061224, 2.59183673, 2.65306122, 2.71428571, 2.7755102 ,
        2.83673469, 2.89795918, 2.95918367, 3.02040816, 3.08163265,
        3.14285714, 3.20408163, 3.26530612, 3.32653061, 3.3877551 ,
        3.44897959, 3.51020408, 3.57142857, 3.63265306, 3.69387755,
        3.75510204, 3.81632653, 3.87755102, 3.93877551, 4.        ],
       [6.        , 5.95918367, 5.91836735, 5.87755102, 5.83673469,
        5.79591837, 5.75510204, 5.71428571, 5.67346939, 5.63265306,
        5.59183673, 5.55102041, 5.51020408, 5.46938776, 5.42857143,
        5.3877551 , 5.34693878, 5.30612245, 5.26530612, 5.2244898 ,
        5.18367347, 5.14285714, 5.10204082, 5.0

In [159]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [147]:
np.logspace([2],[3] ,axis = 0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [148]:
np.logspace([2],[3] ,axis = 1)

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

In [149]:
d = np.linspace(4,7,40)
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [150]:
d.ndim

1

In [151]:
d.shape

(40,)

In [152]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [156]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [157]:
d.reshape(1,2,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [158]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [161]:
np.random.rand(3) # It will produce data based on Normal distribution/gaussian distribution.

array([0.81182075, 0.34115952, 0.78941516])

In [162]:
np.random.randn(5) # It will Return a sample of numbers (or samples) from the "standard normal distribution".

array([-0.33139272, -1.11703314, -0.44549503, -0.85437885, -0.02669858])

In [163]:
np.random.randn(2,2,3)

array([[[-0.14255287, -1.14896331, -1.09906756],
        [-0.11729797,  0.4043128 , -1.09548951]],

       [[-0.66376322, -1.71109944, -1.6686709 ],
        [ 0.80771368, -0.36608303,  1.06834357]]])

In [164]:
np.random.randint(5)

4

In [165]:
np.random.randint(5,60)

30

In [166]:
np.random.randint(5,60,(4,4))

array([[31, 29, 24, 46],
       [59, 38, 51, 42],
       [48, 55, 19, 29],
       [12, 14, 58, 54]])

In [168]:
arr = np.random.randint(3,9,(3,3))
arr

array([[4, 3, 5],
       [6, 5, 5],
       [4, 3, 3]])

In [169]:
arr.reshape(1,9)

array([[4, 3, 5, 6, 5, 5, 4, 3, 3]])

In [170]:
arr.reshape(9,1)

array([[4],
       [3],
       [5],
       [6],
       [5],
       [5],
       [4],
       [3],
       [3]])

In [171]:
arr.reshape(1,1,9)

array([[[4, 3, 5, 6, 5, 5, 4, 3, 3]]])

In [172]:
arr.reshape(3,3,1)

array([[[4],
        [3],
        [5]],

       [[6],
        [5],
        [5]],

       [[4],
        [3],
        [3]]])

In [173]:
arr.reshape(3,-198979)

array([[4, 3, 5],
       [6, 5, 5],
       [4, 3, 3]])

In [174]:
arr.reshape(1,-145654656)

array([[4, 3, 5, 6, 5, 5, 4, 3, 3]])

In [175]:
arr

array([[4, 3, 5],
       [6, 5, 5],
       [4, 3, 3]])

In [176]:
arr.max()

6

In [177]:
arr.min()

3

In [179]:
arr = np.random.randint(4,100, (5,5))
arr

array([[59, 30, 94,  9, 78],
       [70, 71,  7, 90, 44],
       [66, 92, 24, 39, 57],
       [35,  8, 14, 97, 73],
       [99, 66, 32,  8, 45]])

In [180]:
arr[3: , 3:]

array([[97, 73],
       [ 8, 45]])

In [181]:
arr[:,[1,3]]

array([[30,  9],
       [71, 90],
       [92, 39],
       [ 8, 97],
       [66,  8]])

In [182]:
arr

array([[59, 30, 94,  9, 78],
       [70, 71,  7, 90, 44],
       [66, 92, 24, 39, 57],
       [35,  8, 14, 97, 73],
       [99, 66, 32,  8, 45]])

In [184]:
arr>10

array([[ True,  True,  True, False,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True, False,  True]])

In [183]:
arr[arr>10]

array([59, 30, 94, 78, 70, 71, 90, 44, 66, 92, 24, 39, 57, 35, 14, 97, 73,
       99, 66, 32, 45])

In [185]:
arr

array([[59, 30, 94,  9, 78],
       [70, 71,  7, 90, 44],
       [66, 92, 24, 39, 57],
       [35,  8, 14, 97, 73],
       [99, 66, 32,  8, 45]])

In [186]:
arr*arr

array([[3481,  900, 8836,   81, 6084],
       [4900, 5041,   49, 8100, 1936],
       [4356, 8464,  576, 1521, 3249],
       [1225,   64,  196, 9409, 5329],
       [9801, 4356, 1024,   64, 2025]])

In [190]:
arr1 = np.random.randint(2,4,(3,3))
arr1

array([[3, 3, 2],
       [3, 3, 2],
       [2, 3, 2]])

In [189]:
arr2 = np.random.randint(2,4,(3,3))
arr2

array([[2, 2, 3],
       [3, 3, 2],
       [2, 3, 3]])

In [191]:
arr1*arr2

array([[6, 6, 6],
       [9, 9, 4],
       [4, 9, 6]])

In [192]:
arr1@arr2

array([[19, 21, 21],
       [19, 21, 21],
       [17, 19, 18]])

In [193]:
arr/0

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [194]:
arr**2

array([[3481,  900, 8836,   81, 6084],
       [4900, 5041,   49, 8100, 1936],
       [4356, 8464,  576, 1521, 3249],
       [1225,   64,  196, 9409, 5329],
       [9801, 4356, 1024,   64, 2025]])

In [195]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [196]:
a = np.array([1,2,3,5])
a

array([1, 2, 3, 5])

In [197]:
arr + a 

array([[1., 2., 3., 5.],
       [1., 2., 3., 5.],
       [1., 2., 3., 5.]])

In [198]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [199]:
b = np.array([5,6,7])
b

array([5, 6, 7])

In [200]:
b=b.reshape(3,1)
b

array([[5],
       [6],
       [7]])

In [201]:
b + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [204]:
b = np.array([[5,6,7]])
b

array([[5, 6, 7]])

In [203]:
b.T + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [205]:
arr = np.random.rand(5,4)
arr

array([[0.18929521, 0.8484029 , 0.37109952, 0.88056087],
       [0.07288116, 0.12548979, 0.25254976, 0.0447791 ],
       [0.93338298, 0.30545522, 0.61708657, 0.3051688 ],
       [0.38585387, 0.5137722 , 0.68891279, 0.88334617],
       [0.17237062, 0.92152257, 0.99809822, 0.74936367]])

In [206]:
np.sqrt(arr)

array([[0.4350807 , 0.92108789, 0.60917938, 0.93838205],
       [0.2699651 , 0.35424538, 0.50254329, 0.21161072],
       [0.96611748, 0.55268003, 0.78554858, 0.55242085],
       [0.62117137, 0.71677905, 0.8300077 , 0.93986498],
       [0.41517541, 0.95995967, 0.99904866, 0.86565794]])

In [207]:
np.exp(arr)

array([[1.20839763, 2.33591319, 1.4493273 , 2.41225228],
       [1.0756027 , 1.13370359, 1.28730355, 1.04579682],
       [2.54309789, 1.3572427 , 1.85352007, 1.35685402],
       [1.47086972, 1.67158487, 1.99154912, 2.41898051],
       [1.18811809, 2.51311386, 2.71311717, 2.11565332]])

In [208]:
np.log10(arr)

array([[-7.22860371e-01, -7.13978534e-02, -4.30509611e-01,
        -5.52406181e-02],
       [-1.13738475e+00, -9.01391609e-01, -5.97653045e-01,
        -1.34892466e+00],
       [-2.99401227e-02, -5.15052453e-01, -2.09653905e-01,
        -5.15459874e-01],
       [-4.13577138e-01, -2.89229398e-01, -1.61835752e-01,
        -5.38690679e-02],
       [-7.63536760e-01, -3.54940254e-02, -8.26718494e-04,
        -1.25307369e-01]])

In [210]:
arr1 = np.random.randint(2,5,(5,5))
arr1

array([[4, 4, 4, 4, 3],
       [2, 2, 2, 2, 3],
       [2, 2, 3, 2, 2],
       [2, 3, 3, 2, 4],
       [2, 4, 3, 4, 2]])

In [211]:
np.log10(arr1)

array([[0.60205999, 0.60205999, 0.60205999, 0.60205999, 0.47712125],
       [0.30103   , 0.30103   , 0.30103   , 0.30103   , 0.47712125],
       [0.30103   , 0.30103   , 0.47712125, 0.30103   , 0.30103   ],
       [0.30103   , 0.47712125, 0.47712125, 0.30103   , 0.60205999],
       [0.30103   , 0.60205999, 0.47712125, 0.60205999, 0.30103   ]])

In [215]:
np.random.rand(2,4) # If we execute this n no of time so it will give dif dif value every time.

array([[0.25627995, 0.34758122, 0.00941277, 0.35833378],
       [0.94909418, 0.21789901, 0.31939137, 0.91777239]])

In [217]:
np.random.seed(30) # Seed wise we can mention any value.
np.random.rand(2,4) 

# If we execute this n no of time so it will give dif dif value every time, it will give same value in o/p.

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])

In [ ]:
# Open file No.17 directly,no need to open the file no 16.