# Differential Calculus

## Slope of a point on curve

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
x = np.linspace(-10,10,10000)

In [ ]:
y = x**2 + 3*x + 5

In [ ]:
y1 = 7*x + 3

In [ ]:
figure, axes = plt.subplots(dpi=100)
plt.axhline(y=0, color = 'lightgrey')
plt.axvline(x=0, color = 'lightgrey')
plt.axhline(y=2.74)
_ = axes.plot(x,y, color='red')

In [ ]:
figure, axes = plt.subplots(dpi=100)
plt.axhline(y=0, color = 'lightgrey')
plt.axvline(x=0, color = 'lightgrey')
axes.set_xlim(-2.5,0)
axes.set_ylim(1.5,3.5)
plt.axhline(y=2.74)
_ = axes.plot(x,y, color='red')

In [ ]:
figure, axes = plt.subplots(dpi=100)
plt.axhline(y=0, color = 'lightgrey')
plt.axvline(x=0, color = 'lightgrey')
axes.set_xlim(-2,-1)
axes.set_ylim(2.25,3.25)
plt.axhline(y=2.74)
_ = axes.plot(x,y, color='red')

## Curve as a Stirght line

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
x = np.linspace(-5,5,1000)

In [ ]:
y = x**2

In [ ]:
figure, axes = plt.subplots(dpi=100)
_ = axes.plot(x,y)

In [ ]:
figure, axes = plt.subplots(dpi=100)
axes.set_xlim([-2,2])
axes.set_ylim([-1,6])
_ = axes.plot(x,y)

In [ ]:
figure, axes = plt.subplots(dpi=100)
axes.set_xlim([-1,1])
axes.set_ylim([-1,2])
_ = axes.plot(x,y)

In [ ]:
figure, axes = plt.subplots(dpi=100)
axes.set_xlim([-.5,0.5])
axes.set_ylim([-1,2])
_ = axes.plot(x,y)

In [ ]:
figure, axes = plt.subplots(dpi=100)
axes.set_xlim([-.2,.2])
axes.set_ylim([-1,2])
_ = axes.plot(x,y)

In [ ]:
figure, axes = plt.subplots(dpi=100)
axes.set_xlim([-.01,.01])
axes.set_ylim([-1,2])
_ = axes.plot(x,y)

## Limits

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
x = np.linspace(-10,10,10000)

In [ ]:
y = x**2 + 2*x + 3

In [ ]:
figure, axes = plt.subplots(dpi=100)
plt.axhline(y=0, color = 'lightgrey')
plt.axvline(x=0, color = 'lightgrey')

axes.plot(x, y)

In [ ]:
def func(x):
  return x**2 + 2*x + 3

In [ ]:
func(2)

In [ ]:
func(7)

In [ ]:
func(-6)

In [ ]:
func(25)

In [ ]:
figure, axes = plt.subplots(dpi=100)
plt.axhline(y=0, color = 'lightgrey')
plt.axvline(x=0, color = 'lightgrey')

plt.axhline(y = 66, color = 'red', linestyle= '--')
plt.axvline(x=7, color = 'red', linestyle='--')

plt.axhline(y =27, color = 'orange', linestyle= ':')
plt.axvline(x=-6, color = 'orange', linestyle=':')

axes.plot(x, y)

$$ \lim_{x \to 1} \frac{x ^2 -1} {x-1} $$

In [ ]:
y = (x**2 -1)/(x-1)

In [ ]:
figure, axes = plt.subplots(dpi=100)
plt.axhline(y=0, color = 'lightgrey')
plt.axvline(x=0, color = 'lightgrey')

axes.set_ylim(-10,10)

axes.plot(x, y)

In [ ]:
def func(x):
  return (x**2 -1)/(x-1)

In [ ]:
func(2)

In [ ]:
#func(1)

In [ ]:
func(1.00000001)

In [ ]:
func(.999999)

In [ ]:
func(.99999999999999)

In [ ]:
func(4)

In [ ]:
figure, axes = plt.subplots(dpi=100)
plt.axhline(y=0, color = 'lightgrey')
plt.axvline(x=0, color = 'lightgrey')
axes.plot(x, y)

plt.axhline(y = 2, color = 'red', linestyle= '--')
plt.axvline(x=1, color = 'red', linestyle='--')

axes.set_ylim(-10,10)

$$ \lim_{θ \to 1} \frac{\text{tan } θ} {θ} $$

In [ ]:
def func(x):
  return np.tan(x)/x

In [ ]:
func(0)

In [ ]:
func(2)

In [ ]:
func(0.000001)

In [ ]:
func(-.00001)

In [ ]:
y = func(x)

In [ ]:
figure, axes = plt.subplots(dpi=100)
plt.axhline(y=0, color = 'lightgrey')
plt.axvline(x=0, color = 'lightgrey')

axes.set_ylim(-10,10)
axes.plot(x, y)

In [ ]:
figure, axes = plt.subplots(dpi=100)
plt.axhline(y=0, color = 'lightgrey')
plt.axvline(x=0, color = 'lightgrey')

plt.axhline(y=1, color='red', linestyle='--')
plt.axvline(x=0, color='red', linestyle='--')

axes.set_ylim(-10,10)
axes.plot(x, y)

# Derivatives with Delta method

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
x = np.linspace(-10,10,10000)

In [ ]:
def func(x):
  return x**2 + 3*x + 1

In [ ]:
y = func(x)

In [ ]:
figure, axes = plt.subplots(dpi=100)
_ = axes.plot(x,y)

In [ ]:
func(3)

In [ ]:
figure, axes = plt.subplots(dpi=100)
plt.axvline(x=0, color='lightgrey')
plt.axhline(y=0, color='lightgrey')

plt.scatter(3,19, color = 'purple', zorder=3)
_ = axes.plot(x,y)

In [ ]:
func(5)

In [ ]:
figure, axes = plt.subplots(dpi=100)
plt.axvline(x=0, color='lightgrey')
plt.axhline(y=0, color='lightgrey')

plt.scatter(3,19, color = 'purple', zorder=3)
plt.scatter(5,41, color = 'red', zorder=3)
_ = axes.plot(x,y)

In [ ]:
m = (41-19)/(5-3)
m

In [ ]:
c = 41 - 11*5
c

In [ ]:
y1 = m*x + c

In [ ]:
figure, axes = plt.subplots(dpi=100)
plt.axvline(x=0, color='lightgrey')
plt.axhline(y=0, color='lightgrey')

axes.set_ylim(-10,100)

plt.scatter(3,19, color = 'purple', zorder=3)
plt.scatter(5,41, color = 'red', zorder=3)
plt.plot(x,y1, color='orange')
_ = axes.plot(x,y)

In [ ]:
func(3.1)

In [ ]:
figure, axes = plt.subplots(dpi=100)
plt.axvline(x=0, color='lightgrey')
plt.axhline(y=0, color='lightgrey')

plt.scatter(3,19, color = 'purple', zorder=3)
plt.scatter(3.01,19.91, color = 'red', zorder=3)
_ = axes.plot(x,y)

In [ ]:
figure, axes = plt.subplots(dpi=100)
plt.axvline(x=0, color='lightgrey')
plt.axhline(y=0, color='lightgrey')

axes.set_xlim(2.5,3.5)
axes.set_ylim(18.5,20.5)

plt.scatter(3,19, color = 'purple', zorder=3)
plt.scatter(3.1,19.91, color = 'red', zorder=3)
_ = axes.plot(x,y)

In [ ]:
m = (19.91-19)/(3.1-3)
m

In [ ]:
c = 19-m*3
c

In [ ]:
y2 = m*x + c

In [ ]:
figure, axes = plt.subplots(dpi=100)
plt.axvline(x=0, color='lightgrey')
plt.axhline(y=0, color='lightgrey')

axes.set_ylim(-10,100)

plt.scatter(3,19, color = 'purple', zorder=3)
plt.scatter(3.1,19.91, color = 'red', zorder=3)
plt.plot(x,y2, color='orange')
_ = axes.plot(x,y)

In [ ]:
figure, axes = plt.subplots(dpi=100)
plt.axvline(x=0, color='lightgrey')
plt.axhline(y=0, color='lightgrey')

axes.set_xlim(0,5)
axes.set_ylim(15,25)

plt.scatter(3,19, color = 'purple', zorder=3)
plt.scatter(3.1,19.91, color = 'red', zorder=3)
plt.plot(x,y2, color='orange')
_ = axes.plot(x,y)

In [ ]:
def diff(func, x, delta_x):
  return (func(x + delta_x) - func(x))/delta_x

In [ ]:
delta = [1,.1,.01,.001,.0001]

In [ ]:
for i in delta:
  print(diff(func, 3, i))

## differentiation using sympy library

In [1]:
pip install sympy

Note: you may need to restart the kernel to use updated packages.


In [1]:
from sympy import *
import numpy as np

In [ ]:
x = symbols('x')
y = 2
diff(y)

In [ ]:
x = symbols('x')
y = 2*x
diff(y)

In [ ]:
x = symbols('x')
y = 25*x
diff(y)

In [ ]:
x = symbols('x')
y = x
diff(y)

In [ ]:
diff(x, x)

In [ ]:
x = symbols('x')
y = x**2
diff(y)

In [ ]:
diff(x**24, x)

In [ ]:
x = symbols('x')
diff(sin(x), x)

In [ ]:
diff(cos(x), x)

In [ ]:
diff(tan(x),x)

In [ ]:
diff(asin(x),x)

In [ ]:
diff(acos(x),x)

In [ ]:
diff(atan(x), x)

## Sum rule

$$ 2x^3 + x^2 $$

In [ ]:
x = symbols('x')
f = 2*x**3 + x**2
diff(f)

In [ ]:
diff(sin(x)+ cos(x), x)

In [ ]:
diff(sin(x)-cos(x), x)

## Product Rule

$$ (x^2 + 2x)(x-2) $$

In [ ]:
x = symbols('x')
f = (x**2 + 2*x)*(x-2)
diff(f)

## Quotient Rule

$$ \frac{(x^2 + 2x)}{(x-2)} $$

In [ ]:
x = symbols('x')
f = (x**2 + 2*x)/(x-2)
diff(f)

## Chain Rule

In [ ]:
diff((sin(ln(x))**2), x)

In [ ]:
diff((2*x**2 + 5*x)**2, x)

In [ ]:
diff(2*x**2 + 5*x, x)

In [ ]:
diff((sin(ln(x))**2)*(2*x**2 + 5*x)**2, x)

# Application of Differentiation

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sy

In [ ]:
a = [i**2 for i in np.linspace(-3,3,10)]

In [ ]:
plt.plot(a)

In [ ]:
d = np.diff(a)

In [ ]:
plt.plot(d)
plt.axhline(y=0, color = 'lightgrey')
plt.axvline(x=0, color = 'lightgrey')

In [ ]:
b = [np.sin(i) for i in np.linspace(-3,3,10)]

In [ ]:
plt.plot(b)

In [ ]:
d = np.diff(b)

In [ ]:
plt.plot(d)
plt.axhline(y=0, color='lightgrey')

# Autodifferentiation

## Auto differentiation using pytorch

In [1]:
import torch

In [2]:
x = torch.tensor(5.)
x

tensor(5.)

In [3]:
x.requires_grad_()

tensor(5., requires_grad=True)

In [4]:
y = x**2 + 2*x

In [5]:
y.backward()

In [6]:
x.grad

tensor(12.)

In [7]:
x = torch.tensor([2,3,5.]).requires_grad_()
x

tensor([2., 3., 5.], requires_grad=True)

In [8]:
y = x**2 + 2*x

In [10]:
y.sum().backward()

In [11]:
x.grad

tensor([ 6.,  8., 12.])

## Auto Differentiation using TensorFlow

In [12]:
import tensorflow as tf

In [13]:
x = tf.Variable(3.)
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [14]:
with tf.GradientTape() as t:
  t.watch(x)
  y = 2*x**3 + x

In [15]:
t.gradient(y, x)

<tf.Tensor: shape=(), dtype=float32, numpy=55.0>