In [ ]:
import torch

In [ ]:
X = torch.tensor([1,2,3,4,5,6,7,8,9,10.])
X

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
Y = torch.tensor([ 0.7805,  1.8762,  7.8689,  6.8634, 12.0376, 13.9539, 17.2082, 20.4007,
        20.9146, 26.5839])
Y

tensor([ 0.7805,  1.8762,  7.8689,  6.8634, 12.0376, 13.9539, 17.2082, 20.4007,
        20.9146, 26.5839])

In [ ]:
def y_line(x_, m_, c_):
  return x_*m_ + c_

In [ ]:
m = torch.tensor([-2.]).requires_grad_()
m

tensor([-2.], requires_grad=True)

In [ ]:
c = torch.tensor([30.]).requires_grad_()
c

tensor([30.], requires_grad=True)

In [ ]:
x=X[5]
x

tensor(6.)

In [ ]:
y = Y[5]
y

tensor(13.9539)

In [ ]:
y_cap = y_line(x,m,c)
y_cap

tensor([18.], grad_fn=<AddBackward0>)

In [ ]:
def error(y_pred, y_actu): 
    return (y_pred-y_actu)**2

In [ ]:
e = error(y_cap, y)
e

tensor([16.3709], grad_fn=<PowBackward0>)

In [ ]:
e.backward()

In [ ]:
m.grad

tensor([48.5532])

In [ ]:
c.grad

tensor([8.0922])

In [ ]:
2*x*(y_cap-y)

tensor([48.5532], grad_fn=<MulBackward0>)

In [ ]:
2*(y_cap-y)

tensor([8.0922], grad_fn=<MulBackward0>)

In [ ]:
grad = torch.tensor([[c.grad.item(), m.grad.item()]]).T
grad

tensor([[ 8.0922],
        [48.5532]])