In [ ]:
import torch

In [ ]:
x = torch.tensor([1,2,3,4,5,6,7,8,9,10.])
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
y = torch.tensor([ 0.7805,  1.8762,  7.8689,  6.8634, 12.0376, 13.9539, 17.2082, 20.4007,
        20.9146, 26.5839])
y

tensor([ 0.7805,  1.8762,  7.8689,  6.8634, 12.0376, 13.9539, 17.2082, 20.4007,
        20.9146, 26.5839])

In [ ]:
m = torch.tensor([-2.]).requires_grad_()
m

tensor([-2.], requires_grad=True)

In [ ]:
c = torch.tensor([30.]).requires_grad_()
c

tensor([30.], requires_grad=True)

In [ ]:
def y_line(x_, m_, c_):
  return x_*m_ + c_

In [ ]:
y_cap = y_line(x,m,c)
y_cap

tensor([28., 26., 24., 22., 20., 18., 16., 14., 12., 10.],
       grad_fn=<AddBackward0>)

In [ ]:
def error(y_pred, y_actu): 
    sigma = torch.sum((y_pred - y_actu)**2)
    return sigma/len(y_actu)

In [ ]:
e = error(y_cap, y)
e

tensor(228.8883, grad_fn=<DivBackward0>)

In [ ]:
e.backward()

In [ ]:
m.grad

tensor([-11.4476])

In [ ]:
c.grad

tensor([12.3024])

In [ ]:
2*(1/len(x))* torch.sum((y_cap-y)*x)

tensor(-11.4476, grad_fn=<MulBackward0>)

In [ ]:
2*(1/len(x))* torch.sum(y_cap-y)

tensor(12.3024, grad_fn=<MulBackward0>)

In [ ]:
grad = torch.tensor([[c.grad.item(), m.grad]]).T
grad

tensor([[ 12.3024],
        [-11.4476]])